language: python
sudo: false
cache: pip

python:
  - "3.4"
  - "2.7"

env:
  - DJANGO="django>=1.11,<1.12"
  - DJANGO="django>=2.0,<2.1"

matrix:
  exclude:
   - python: "2.7"
     env: DJANGO="django>=2.0,<2.1"

branches:
  only:
    - master

before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt
  - ./runflake8
  - ./runisort
  - npm install -g jslint
  - jslint django_netjsonconfig/static/django-netjsonconfig/js/*.js

install:
  - pip install $DJANGO
  - pip install https://github.com/openwisp/django-x509/tarball/master
  - python setup.py -q develop

script:
  - coverage run --source=django_netjsonconfig runtests.py

after_success:
  coveralls
